baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Matthew R. Hennefarth'
copyright = '© 2023 Matthew R. Hennefarth'
enableInlineShortcodes = true
DefaultContentLanguage = 'en'

[Taxonomies]

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[params]
noindex = false

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/matthew-hennefarth"

[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "Twitter"
url = "https://twitter.com/m_hennefarth"

[[params.socialLinks]]
icon = "ai ai-orcid"
title = 'ORCID'
url = "https://orcid.org/0000-0002-6601-2253"

[[params.socialLinks]]
icon = "ai ai-google-scholar"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=Sds3I_QAAAAJ&hl=en&oi=ao"

[[params.socialLinks]]
icon = "ai ai-cv"
title = "CV"
url = "/cv.pdf"

[menu]

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 10

[params.about]
title = "Matthew R. Hennefarth"
description = "PhD. Candidate in Chemistry at UChicago"

[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params.seo.webmaster_verifications]
google = "YZYpnVOuBd0u3qwa22vRjiTPrOGELzPs6PKzceC71z8"
